Rails/ActionView/config/routes.rb
Rails.application.routes.draw do
  resources :people
  resources :states
  resources :countries
  resources :answers
  resources :questions
  resources :surveys
  resources :books
  resources :authors
  resources :products
  resources :categories
  resources :orders do
    member do
      put :change_state,  as: :change_state
    end
  end

  root 'static_pages#home'

  resources :articles

end

Rails/ActionView/app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

Rails/ActionView/app/models/article.rb
class Article < ActiveRecord::Base
end

Rails/ActionView/app/models/author.rb
class Author < ActiveRecord::Base
  has_many :authorships
  has_many :books, through: :authorships

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: "invalid email format"

  def self.tokens query
    authors = Author.where("name like ?", "%#{query}%")
    if authors.empty?
      [{id: "<<<#{query}>>>", name: "New: \"#{query}\" "}]
    else
      authors
    end
  end

  def self.ids_from_tokens tokens
    tokens.gsub!(/<<<(.+?)>>>/) {create!(name: $1).id }
    tokens.split(',')
  end

end

Rails/ActionView/app/models/authorship.rb
class Authorship < ActiveRecord::Base
  belongs_to :book
  belongs_to :author
end

Rails/ActionView/app/models/book.rb
class Book < ActiveRecord::Base
  has_many :authorships
  has_many :authors, through: :authorships
  attr_reader :author_tokens

  def author_tokens=(tokens)
    self.author_ids = Author.ids_from_tokens(tokens)
  end

end

Rails/ActionView/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :states
end

Rails/ActionView/app/models/country.rb
class Country < ActiveRecord::Base
  has_many :states
end

Rails/ActionView/app/models/order.rb
class Order < ActiveRecord::Base
  scope :open_orders, -> { with_state(:open) }
  scope :new_orders, -> { with_state(:incomplete) }

  state_machine  initial: :incomplete do

    event :purchase do
      transition :incomplete =>  :open
    end

    event :cancel do
      transition :open => :canceled
    end

    event :resume do
      transition :canceled => :open
    end

    event :ship do
      transition :open => :shippednene
    end

  end


  def self.total_grouped_by_day(start)
    orders = where(purchased_at: start.beginning_of_day..Time.zone.now)
    orders = orders.group('date(purchased_at)')
    orders = orders.select('purchased_at, sum(price) as total_price')
    orders.group_by { |o| o.purchased_at.to_date }
  end

end

Rails/ActionView/app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :country
  belongs_to :state
end

Rails/ActionView/app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category

  def category_name
    category.try(:name)
  end

  def category_name=(name)
    self.category = Category.find_or_create_by(name: name) if name.present?
  end
end

Rails/ActionView/app/models/product_field.rb
class ProductField < ActiveRecord::Base
  belongs_to :product_type
end

Rails/ActionView/app/models/product_type.rb
class ProductType < ActiveRecord::Base
  has_many :products
  has_many :fields, class_name: 'ProductField'
  accepts_nested_attributes_for :fields, allow_destroy: true
end

Rails/ActionView/app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  has_many :answers, dependent: :destroy

  accepts_nested_attributes_for :answers,
                                reject_if: lambda { |a| a[:content].blank? },
                                allow_destroy: true
end

Rails/ActionView/app/models/state.rb
class State < ActiveRecord::Base
  belongs_to :country
end

Rails/ActionView/app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :questions, dependent: :destroy

  accepts_nested_attributes_for :questions,
                                reject_if: lambda { |a| a[:content].blank? },
                                allow_destroy: true

end

Rails/ActionView/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy, :change_state]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.paginate(:page => params[:page], :per_page => 30)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def change_state
    events = @order.state_events
    respond_to do |format|
      if events && @order.send(events[0])
        format.html { redirect_to @order, notice: "Order was successfully updated to state #{@order.state}." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { redirect_to order_url, notice: 'Order was not updated.' }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:order_number, :card_last_four, :amount, :credit_card_number, :credit_card_expires_on)
    end
end

Rails/ActionView/app/helpers/answers_helper.rb
module AnswersHelper
end

Rails/ActionView/app/helpers/authors_helper.rb
module AuthorsHelper
end

Rails/ActionView/app/helpers/books_helper.rb
module BooksHelper
end

Rails/ActionView/app/helpers/orders_helper.rb
module OrdersHelper
  def orders_chart_data(start = 5.weeks.ago)
    orders_by_date = Order.total_grouped_by_day(start)
    shipping_by_date = Order.where(shipping: true).total_grouped_by_day(start)
    download_by_date = Order.where(shipping: false).total_grouped_by_day(start)

    (3.weeks.ago.to_date..Date.today).map do |date|
      {
        purchased_at: date,
        price: orders_by_date[date].try(:first).try(:total_price) || 0,
        shipping_price: shipping_by_date[date].try(:first).try(:total_price) || 0,
        download_price: download_by_date[date].try(:first).try(:total_price) || 0
      }
    end
  end
end

Rails/ActionView/app/helpers/people_helper.rb
module PeopleHelper
end

Rails/ActionView/app/helpers/states_helper.rb
module StatesHelper
end

Rails/ActionView/app/helpers/surveys_helper.rb
module SurveysHelper
end

Rails/ActionView/app/views/orders/_chart.html.erb
<%= content_tag :div, '', id: 'orders_chart', data: { orders: orders_chart_data } %>

Rails/ActionView/app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :order_number %><br>
    <%= f.text_field :order_number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :card_last_four %><br>
    <%= f.text_field :card_last_four, class: 'form-control' %>
    <span id="last_four_error" class="label label-danger"></span>
  </div>
  <div class="form-group">
    <%= f.label :amount %><br>
    <%= f.text_field :amount, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :credit_card_number %><br>
    <%= f.text_field :credit_card_number, class: 'form-control' %>
    <span id="credit_card_number_error" class="label label-danger"></span>
  </div>
  <div class="form-group">
    <%= f.label :credit_card_expires_on %><br>
    <%= f.text_field :credit_card_expires_on %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn' %>
  </div>
<% end %>

Rails/ActionView/app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

Rails/ActionView/app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<%= render 'chart' %>

<%= link_to 'New Order', new_order_path %>
<table class="table">
  <thead>
    <tr>
      <th>Order number</th>
      <th>Amount</th>
      <th>Purchased</th>
      <th>Shipping</th>
      <th>Price</th>
      <th>State</th>
      <th>Possible events</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.order_number %></td>
        <td><%= order.amount %></td>
        <td><%= order.purchased_at.strftime("%B %e, %Y %H:%M") %></td>
        <td><%= order.shipping ? "Yes" : "No" %></td>
        <td><%= number_to_currency order.price %></td>
        <td><%= order.state %></td>
        <td><%= order.state_events %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Change state', change_state_order_path(order), method: :put %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @posts %>
<br>

Rails/ActionView/app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

Rails/ActionView/app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order number:</strong>
  <%= @order.order_number %>
</p>

<p>
  <strong>Card last four:</strong>
  <%= @order.card_last_four %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @order.amount %>
</p>

<p>
  <strong>Credit card number:</strong>
  <%= @order.credit_card_number %>
</p>

<p>
  <strong>Credit card expires on:</strong>
  <%= @order.credit_card_expires_on %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>