Rails/ActionView/config/routes.rb
Rails.application.routes.draw do
  resources :people
  resources :states
  resources :countries
  resources :answers
  resources :questions
  resources :surveys
  resources :books
  resources :authors
  resources :products
  resources :categories
  resources :orders do
    member do
      put :change_state,  as: :change_state
    end
  end

  root 'static_pages#home'

  resources :articles

end

Rails/ActionView/app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

Rails/ActionView/app/models/article.rb
class Article < ActiveRecord::Base
end

Rails/ActionView/app/models/author.rb
class Author < ActiveRecord::Base
  has_many :authorships
  has_many :books, through: :authorships

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: "invalid email format"

  def self.tokens query
    authors = Author.where("name like ?", "%#{query}%")
    if authors.empty?
      [{id: "<<<#{query}>>>", name: "New: \"#{query}\" "}]
    else
      authors
    end
  end

  def self.ids_from_tokens tokens
    tokens.gsub!(/<<<(.+?)>>>/) {create!(name: $1).id }
    tokens.split(',')
  end

end

Rails/ActionView/app/models/authorship.rb
class Authorship < ActiveRecord::Base
  belongs_to :book
  belongs_to :author
end

Rails/ActionView/app/models/book.rb
class Book < ActiveRecord::Base
  has_many :authorships
  has_many :authors, through: :authorships
  attr_reader :author_tokens

  def author_tokens=(tokens)
    self.author_ids = Author.ids_from_tokens(tokens)
  end

end

Rails/ActionView/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :states
end

Rails/ActionView/app/models/country.rb
class Country < ActiveRecord::Base
  has_many :states
end

Rails/ActionView/app/models/order.rb
class Order < ActiveRecord::Base
  scope :open_orders, -> { with_state(:open) }
  scope :new_orders, -> { with_state(:incomplete) }

  state_machine  initial: :incomplete do

    event :purchase do
      transition :incomplete =>  :open
    end

    event :cancel do
      transition :open => :canceled
    end

    event :resume do
      transition :canceled => :open
    end

    event :ship do
      transition :open => :shippednene
    end

  end


  def self.total_grouped_by_day(start)
    orders = where(purchased_at: start.beginning_of_day..Time.zone.now)
    orders = orders.group('date(purchased_at)')
    orders = orders.select('purchased_at, sum(price) as total_price')
    orders.group_by { |o| o.purchased_at.to_date }
  end

end

Rails/ActionView/app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :country
  belongs_to :state
end

Rails/ActionView/app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category

  def category_name
    category.try(:name)
  end

  def category_name=(name)
    self.category = Category.find_or_create_by(name: name) if name.present?
  end
end

Rails/ActionView/app/models/product_field.rb
class ProductField < ActiveRecord::Base
  belongs_to :product_type
end

Rails/ActionView/app/models/product_type.rb
class ProductType < ActiveRecord::Base
  has_many :products
  has_many :fields, class_name: 'ProductField'
  accepts_nested_attributes_for :fields, allow_destroy: true
end

Rails/ActionView/app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  has_many :answers, dependent: :destroy

  accepts_nested_attributes_for :answers,
                                reject_if: lambda { |a| a[:content].blank? },
                                allow_destroy: true
end

Rails/ActionView/app/models/state.rb
class State < ActiveRecord::Base
  belongs_to :country
end

Rails/ActionView/app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :questions, dependent: :destroy

  accepts_nested_attributes_for :questions,
                                reject_if: lambda { |a| a[:content].blank? },
                                allow_destroy: true

end

Rails/ActionView/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
    respond_to do |format|
      format.html {}
      format.json { render json: @authors.tokens(params[:q]) }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :email, :gender, :public_profile, :bio)
    end
end

Rails/ActionView/app/helpers/answers_helper.rb
module AnswersHelper
end

Rails/ActionView/app/helpers/authors_helper.rb
module AuthorsHelper
end

Rails/ActionView/app/helpers/books_helper.rb
module BooksHelper
end

Rails/ActionView/app/helpers/orders_helper.rb
module OrdersHelper
  def orders_chart_data(start = 5.weeks.ago)
    orders_by_date = Order.total_grouped_by_day(start)
    shipping_by_date = Order.where(shipping: true).total_grouped_by_day(start)
    download_by_date = Order.where(shipping: false).total_grouped_by_day(start)

    (3.weeks.ago.to_date..Date.today).map do |date|
      {
        purchased_at: date,
        price: orders_by_date[date].try(:first).try(:total_price) || 0,
        shipping_price: shipping_by_date[date].try(:first).try(:total_price) || 0,
        download_price: download_by_date[date].try(:first).try(:total_price) || 0
      }
    end
  end
end

Rails/ActionView/app/helpers/people_helper.rb
module PeopleHelper
end

Rails/ActionView/app/helpers/states_helper.rb
module StatesHelper
end

Rails/ActionView/app/helpers/surveys_helper.rb
module SurveysHelper
end

Rails/ActionView/app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/ActionView/app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

Rails/ActionView/app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Authors</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

Rails/ActionView/app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

Rails/ActionView/app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= best_in_place @author, :name %>
</p>

<p>
  <strong>Email:</strong>
  <%= best_in_place @author, :email %>
</p>
<p>
  <b>Gender:</b>
  <%= best_in_place @author, :gender,  :as => :select, collection: [["Male", "Male"], ["Female", "Female"], ["", "Unspecified"]] %>
</p>
<p>
  <b>Public profile:</b>
  <%= best_in_place @author, :public_profile, as: :checkbox, collection: %w[No Yes] %>
</p>
<p>
  <b>Bio</b>
  <%= best_in_place @author, :bio, :as => :textarea %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>