Rails/portfolio_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]
  get 'welcome/index'
  root 'welcome#index'
  get '*path' => redirect('/')

end

Rails/portfolio_app/app/models/contact.rb
class Contact <  MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true


  def headers
    {
      :to => "alina.grishchuk91@gmail.com",
      :subject => "Contact form",
      :from => %("#{name} <#{email}")
    }
  end
end

Rails/portfolio_app/app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  validates_presence_of :content, :title
end

Rails/portfolio_app/app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

Rails/portfolio_app/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Rails/portfolio_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Rails/portfolio_app/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

Rails/portfolio_app/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts  = Post.order("created_at desc").paginate(page: params[:page], per_page: 10)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params
    if @post.save
      redirect_to @post,  notice: 'post created!'
    else
      render 'new', notice: 'unable to save!'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update post_params
      redirect_to @post,  notice: 'post updated!'
    else
      render 'edit', notice: 'unable to save!'
    end
  end
  def destroy
    @post.destroy
    redirect_to posts_path,  notice: 'post deleted!'
  end

  private
    def post_params
      params.require(:post).permit(:title, :content, :slug)
    end
    def find_post
      @post = Post.friendly.find(params[:id])
    end
end

Rails/portfolio_app/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @projects = Project.order("created_at desc").paginate(page: params[:page], per_page: 10)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new project_params
    if @project.save
      redirect_to @project,  notice: 'post created!'
    else
      render 'new', notice: 'unable to save!'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update project_params
      redirect_to @project,  notice: 'project updated!'
    else
      render 'edit', notice: 'unable to save!'
    end
  end
  def destroy
    @project.destroy
    redirect_to projects_path,  notice: 'project deleted!'

  end

  private
  def project_params
    params.require(:project).permit(:title, :description, :link, :slug)
  end
  def find_project
    @project = Project.friendly.find(params[:id])
  end
end

Rails/portfolio_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.order("created_at desc").limit(3)
    @projects = Project.order("created_at desc").limit(3)
  end
end

Rails/portfolio_app/app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end
  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

Rails/portfolio_app/app/helpers/contacts_helper.rb
module ContactsHelper
end

Rails/portfolio_app/app/helpers/posts_helper.rb
module PostsHelper
end

Rails/portfolio_app/app/helpers/projects_helper.rb
module ProjectsHelper
end

Rails/portfolio_app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Rails/portfolio_app/app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
  var disqus_config = function () {
    this.page.url = '<%= url_for([@post, {only_path: false}]) %>';
    this.page.title = '<%= @post.title %>';
    this.page.identifier = '<%= @post.id %>';
  };

   (function() {
     var d = document, s = d.createElement('script');
     s.src = '//myblogsitetmp.disqus.com/embed.js';
     s.setAttribute('data-timestamp', +new Date());
     (d.head || d.body).appendChild(s);
   })();
</script>
<noscript>
  Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a>
</noscript>

Rails/portfolio_app/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
    <ul>
      <% @post.errors.full_message.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title %><br>
  <%= f.text_field :title %><br>

  <%= f.label :content , "Write article here !" %><br>
  <%= f.text_area :content %>

  <br>
  <br>
  <%= f.submit %>
<% end %>

Rails/portfolio_app/app/views/posts/edit.html.erb
<h1>Edit post!</h1>
<%= render 'form' %>

Rails/portfolio_app/app/views/posts/index.html.erb
<h1 id="page_title">Stuff I've Written</h1>

<div id="posts_wrapper" class="skinny_wrapper">
  <% @posts.each do |post| %>
      <div class="post">
        <p class="date"><%= post.created_at.strftime('%A, %B %d') %></p>
        <h2><a href="#"><%= link_to post.title, post %></a></h2>
        <hr>
      </div>
  <% end %>
</div>

<%= will_paginate @posts %>

Rails/portfolio_app/app/views/posts/new.html.erb
<h1 id="page_title">New post!</h1>
<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
</div>

Rails/portfolio_app/app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
  <header>
    <p class="date"><%= @post.created_at.strftime('%A, %B %d') %></p>
    <h1><%= @post.title %></h1>
  </header>

  <hr>

  <div id="content">
    <%=  markdown @post.content %>
  </div>

  <% if user_signed_in? %>
    <div id="admin_links">
      <%= link_to "Edit Article", edit_post_path(@post) %>
      <%= link_to "Delete Article", post_path(@post), method: :delete, data: { confirm: "Are you sure?" } %>
    </div>
  <% end %>

  <hr>

  <div id="share_box">
    <p>Share</p>
    <!-- Twitter -->
    <i class="fa fa-twitter"></i>
    <!-- Facebook -->
    <i class="fa fa-facebook"></i>
    <!-- Google Plus -->
    <i class="fa fa-google-plus"></i>
  </div>

  <hr>

  <%= render 'disqus' %>
</div>

Rails/portfolio_app/app/views/shared/_footer.html.erb
<footer id="main_footer">
  <p class="copyright">
    &copy; some copyrights
  </p>
  <nav>
    <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
    <a href="#" target="_blank"><i class="fa fa-dribbble"></i></a>
    <a href="#" target="_blank"><i class="fa fa-github"></i></a>
  </nav>
</footer>

Rails/portfolio_app/app/views/shared/_header.html.erb
<header id="main_navigation" class="clearfix">
  <%= link_to "My Portfolio", root_path, class: "name" %>
  <nav>
    <%= link_to "Posts", posts_path %>
    <%= link_to "Projects", projects_path %>
    <%= link_to "Contacts", new_contact_path %>
    <% if user_signed_in? %>
      <%= link_to "Log out", destroy_user_session_path, :method => :delete %>
    <% else %>
      <%= link_to('Log in', new_user_session_path) %>
    <% end %>
  </nav>
</header>